---
title: "Calendar for 500: Spring 2025"
date-modified: last-modified
---

This Calendar serves as the final word on all deadlines, deliverables and class sessions. 

## Timing and Location

- Thanks to Dr. Love's broken leg, this year's 500 class will be held **remotely** before Spring Break, and then in person starting March 20.
- The first eight classes will be held via Zoom from **10-11 AM** on Thursday mornings.
- In person classes (Classes 9-14) will be held on Thursdays from **9:00 - 11:15 AM** in Wolstein Research Building, Room 1217.

## Email and Office Hours

- Contact Dr. Love at **thomas** dot **love** at **case** dot **edu** if you have any questions, any time after 2025-01-06.
- Dr. Love will hold office hours after class for 30 minutes. Just let him know during class if you want to speak with him afterwards.
- For more information, visit [Contact Us](contact.qmd).

## Readings

During the course, we will read Paul Rosenbaum's book **Causal Inference** (abbreviated **PRR CI** below), which is available as an e-book or in paperback for under $15. Please obtain the book before our first class on 2025-01-16, and get started reading it as soon as possible.


## February 2025

### [Class 04 (2025-02-06) link](https://github.com/THOMASELOVE/500-classes-2025/tree/main/class04)

Zoom class 4 will take place on Thursday 2025-02-06 from 10-11 AM. Complete the following prior to that session:

- Watch recorded Lecture 4: Doing all of this in R: The toy example
- The [Examples section of our website](https://thomaselove.github.io/500-examples/) provides [the toy example](https://thomaselove.github.io/500-examples/toy_analysis.html), as well as [the lindner example](https://thomaselove.github.io/500-examples/#the-lindner-example), which does a lot of the same things in a slightly different way.
- Begin drafting your [Project](proj500.qmd) Proposal, which is due next week.
- Complete reading before Class 4: 
  1. **PRR CI** through Chapter 5,
  2. Skim Normand 2001 from [Sources](https://github.com/THOMASELOVE/500-sources)

### [Class 05 (2025-02-13) link](https://github.com/THOMASELOVE/500-classes-2025/tree/main/class05)

Zoom class 5 will take place on Thursday 2025-02-13 from 10-11 AM. Complete the following prior to that session:

- Watch recorded Lecture 5: The lindner example, The dm2200 example, Choosing a Matching Approach
- Complete and submit [Project](proj500.qmd) Proposal Draft 1 to Canvas by **9 AM on 2025-02-13**.
- Complete reading before Class 5: 
  1. **PRR CI** through Chapter 6 (which is very short.)
  2. Austin 2014 Comparing 12 PS Matching algorithms (see [our Sources page](https://github.com/THOMASELOVE/500-sources/blob/main/articles/Austin%202014%20Comparing%2012%20PS%20matching%20algorithms.pdf)) 
  3. Skim Ahmed MI et al 2012 (see [our Sources page](https://github.com/THOMASELOVE/500-sources/blob/main/articles/Ahmed%20et%20al%202012%20Int%20J%20Card.pdf)) 
 
### [Class 06 (2025-02-20) link](https://github.com/THOMASELOVE/500-classes-2025/tree/main/class06)

Zoom class 6 will take place on Thursday 2025-02-20 from 10-11 AM. Complete the following prior to that session:

- Watch recorded Lecture 6: Rubin (2001) and Rubin's Rules in [our examples](https://thomaselove.github.io/500-examples/), Austin & Mamdani
- Complete and submit [Lab 2](lab2.qmd) to Canvas by **9 AM on 2025-02-20**.
- Email [OSIA selections](osia.qmd) to **Thomas** dot **Love** at **case** dot **edu** by **9 AM on Wednesday 2025-02-19**.
- Complete reading before Class 6: 
  1. Read Rubin 2001 from [Sources](https://github.com/THOMASELOVE/500-sources)
  2. Skim Austin and Mamdani 2006, from [Sources](https://github.com/THOMASELOVE/500-sources)
  3. Skim Kubo 2020 from [Sources](https://github.com/THOMASELOVE/500-sources)
  4. Skim Hansen 2004 from [Sources](https://github.com/THOMASELOVE/500-sources)

### [Class 07 (2025-02-27) link](https://github.com/THOMASELOVE/500-classes-2025/tree/main/class07)

Zoom class 7 will take place on Thursday 2025-02-27 from 10-11 AM. Complete the following prior to that session:

- By 9 AM on **Wednesday 2025-02-26**, please complete [this Google Form](https://forms.gle/HkTWtzJnzrzoKjx88) (you'll need to be logged into Google via CWRU to see the form) to specify your three top choices for OSIA presentations on which to serve as "[second reader](https://thomaselove.github.io/500-2025/osia.html#second-reader)". 
    - The [list of OSIA claims is here](https://github.com/THOMASELOVE/500-classes-2025/tree/main/osia), and the PDFs are posted on [the claims page](https://github.com/THOMASELOVE/500-classes-2025/tree/main/osia), and also posted on our Shared Drive.
- Complete and submit [Project](proj500.qmd) Proposal Draft 2 to Canvas by **9 AM on Thursday 2025-02-27**.
- **Warning**: Be prepared. In the Zoom meeting on 2025-02-27, each of you will give a 2-3 minute talk in which you will *briefly* describe the title, population, outcome, treatment and covariates included in your second Project Proposal draft.
    - I have prepared a set of 3-4 slides for each of you, which are now available (.qmd and .html files) on our Shared Drive in the Project Proposal Presentation Slides (First Drafts by TEL) folder.  
    - **NEW PART OF THE ASSIGNMENT** Part of your job in submitting Draft 2 is now to download the qmd version of that document I've set up for you, then edit it, as appropriate, to include your covariates, respond to any requests in the document, and then upload the resulting qmd file (now with a filename indicating this is draft2, instead of draft1) to Canvas by the same deadline of Thursday February 27 at 9 AM.
    - I will then grab those revised slides, and show them on screen as you give your presentation in class on February 27 at 10 AM. 
    - If you will not be able to attend class that day, please email me to let me know. I've probably forgotten - if you're in that situation, we'll have you talk to your slides the next week.
- Watch recorded Lecture 7: The SUPPORT Study, Sensitivity Analyses after Matching
- Complete reading before Class 7: 
  1. Read Connors 1996 from [Sources](https://github.com/THOMASELOVE/500-sources)
  2. Skim D'Agostino Jr 1998 from [Sources](https://github.com/THOMASELOVE/500-sources)

## March 2025

### [Class 08 (2025-03-06) link](https://github.com/THOMASELOVE/500-classes-2025/tree/main/class08)

Zoom class 8 will take place on Thursday 2025-03-06 from 10-11 AM. Complete the following prior to that session:

- Watch recorded Lecture 8: Extensions to Matching, Instrumental Variables
- Complete and submit [Lab 3](lab3.qmd) to Canvas by **9 AM on 2025-03-06**.
- Complete reading before Class 8: 
  1. **PRR CI** through Chapter 7.
  2. Read Whitehouse 2007 from [Sources](https://github.com/THOMASELOVE/500-sources)
  3. Skim Landrum and Ayanian 2001 from [Sources](https://github.com/THOMASELOVE/500-sources)
  4. Skim Tanenbaum 2019 from [Sources](https://github.com/THOMASELOVE/500-sources)

### Spring Break includes 2025-03-13

### Class 09 (2025-03-20)

This, I hope, will be our first in-person class, starting at 9 AM and running until 11:15 AM in Wolstein Research Building, room 1217.

- Complete and submit [Lab 4](lab4.qmd) to Canvas by **8 AM on 2025-03-20**.
- OSIA session 1 (schedule TBA)
- Complete reading of **PRR CI** through Chapter 8.
- Skim Elbadawi 2021 from [Sources](https://github.com/THOMASELOVE/500-sources)

### Class 10 (2025-03-27)

Again, I hope this will be in person, starting at 9 AM and running until 11:15 AM in Wolstein Research Building, room 1217.

- [Project Update](https://thomaselove.github.io/500-2025/proj500.html#the-project-update) due to Canvas at 9 AM on Wednesday 2025-03-26.
- OSIA session 2 (schedule TBA)
- Complete reading of **PRR CI** through Chapter 9.
- Skim Posner 2001 from [Sources](https://github.com/THOMASELOVE/500-sources)

## April 2025

### Class 11 (2025-04-03)

Again, I hope this will be in person, starting at 9 AM and running until 11:15 AM in Wolstein Research Building, room 1217.

- OSIA session 3 (schedule TBA)
- Final discussion and Q&A for projects before presentations (which start next week.)

### Class 12 (2025-04-10)

This should be in person, starting at 9 AM and running until 11:15 AM in Wolstein Research Building, room 1217.

- Project Presentations group A (schedule TBA)

### Class 13 (2025-04-17)

This should be in person, starting at 9 AM and running until 11:15 AM in Wolstein Research Building, room 1217.

- Project Presentations group B (schedule TBA)

### Class 14 (2025-04-24)

This should be in person, starting at 9 AM and running until 11:15 AM in Wolstein Research Building, room 1217.

- Project Presentations group C (schedule TBA)

## Final Deadlines

- Final Project Submissions are due to [Canvas](https://canvas.case.edu/) at **9 AM on Monday 2025-04-28** from everyone regardless of when you give your project presentation.
- When prompted via email by the University (usually in late April), please visit <https://webapps.case.edu/courseevals/> and complete the course evaluations before they close.


## January 2025

### [Class 01 (2025-01-16) Link](https://github.com/THOMASELOVE/500-classes-2025/tree/main/class01)

Zoom class 1 will take place on Thursday 2025-01-16 from 10-11 AM. Complete the following prior to that session:

- Watch recorded Lecture 1: RCTs and Observational Studies; A Motivating Example
- Complete reading before Class 1: 
  - Benson and Hartz 2000 from [Sources](https://github.com/THOMASELOVE/500-sources)
  - **PRR CI** through Chapter 2, if possible.

### [Class 02 (2025-01-23) Link](https://github.com/THOMASELOVE/500-classes-2025/tree/main/class02)

Zoom class 2 will take place on Thursday 2025-01-23 from 10-11 AM. Complete the following prior to that session:

- Watch recorded Lecture 2: STROBE, HRT, Assessing Causal Effects, Propensity Score
- Get R and RStudio plus the necessary R packages installed/updated on your machine, following the [software](software.qmd) instructions.
- Work through [Lab 0](lab0.qmd), referring to the [template and sketch](lab0.qmd). There's nothing to turn in, but it will help with future labs.
- Complete reading before Class 2: 
  1. **PRR CI** through Chapter 3,
  2. Abramson Chapter 2 from [Sources](https://github.com/THOMASELOVE/500-sources),
  3. McGowan blog post from [Sources](https://github.com/THOMASELOVE/500-sources),
  4. Bradford Hill 1965 from [Sources](https://github.com/THOMASELOVE/500-sources).

### [Class 03 (2025-01-30) Link](https://github.com/THOMASELOVE/500-classes-2025/tree/main/class03)

Zoom class 3 will take place on Thursday 2025-01-30 from 10-11 AM. Complete the following prior to that session:

- Watch recorded Lecture 3: Building the PS Model, Matching/Stratification/Adjustment, Love Plots
- Complete and Submit [Lab 1](lab1.qmd) to [Canvas](https://canvas.case.edu/) by **9 AM** on 2025-01-30.
- Your [OSIA selections](osia.qmd) to **Thomas** dot **Love** at **case** dot **edu** by **9 AM on Wednesday, 2025-02-19** but you can send them earlier to lock that in.
- Complete reading before Class 3: 
  1. **PRR CI** through Chapter 4,
  2. Gum 2001 from [Sources](https://github.com/THOMASELOVE/500-sources),
  3. skim Connors 1996 from [Sources](https://github.com/THOMASELOVE/500-sources)


